In [ ]:
# install pytorch then import

# Basic Operations

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.empty(3) # create 1D tensor of size 3; add more numbers for higher dimensions
print(x)

tensor([-2.7966e-29,  4.4322e-41,  2.3140e-33])


In [ ]:
x = torch.rand(5, 3)
print(x)
print(x[1, 1])
print(x[:, 2])
print(x[1, :])

tensor([[0.0487, 0.8774, 0.9829],
        [0.8283, 0.6321, 0.5960],
        [0.5476, 0.6583, 0.4423],
        [0.6647, 0.8722, 0.7679],
        [0.9290, 0.7206, 0.2262]])
tensor(0.6321)
tensor([0.9829, 0.5960, 0.4423, 0.7679, 0.2262])
tensor([0.8283, 0.6321, 0.5960])


In [ ]:
x = torch.rand(4, 4)
print(x)
y = x.view(16) # puts tensor values in one dimension
print(y)

tensor([[0.3199, 0.3054, 0.1873, 0.7865],
        [0.9565, 0.2925, 0.6158, 0.0753],
        [0.2853, 0.1798, 0.9922, 0.2626],
        [0.8066, 0.4766, 0.8138, 0.3130]])
tensor([0.3199, 0.3054, 0.1873, 0.7865, 0.9565, 0.2925, 0.6158, 0.0753, 0.2853,
        0.1798, 0.9922, 0.2626, 0.8066, 0.4766, 0.8138, 0.3130])


In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))
a.add_(1) # will modify both a and b if on CPU
print(a)
print(b)

# changing from numpy to tensor is same

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# create tensor on gpu (2 diff ways)
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y # will be performed on the GPU so may be much faster
    z.numpy() # will not work because numpy cannot handle GPU tensors
    z = z.to("cpu")

In [ ]:
x = torch.ones(5, requires_grad=True) # by defualt false; used for optimization
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# Autograd Package and Calculating Gradients

In [ ]:
import torch

In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y * y * 2
print(z)
z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([ 0.3205, -0.3937, -0.8773], requires_grad=True)
tensor([2.3205, 1.6063, 1.1227], grad_fn=<AddBackward0>)
tensor([10.7697,  5.1605,  2.5208], grad_fn=<MulBackward0>)
tensor(6.1503, grad_fn=<MeanBackward0>)
tensor([3.0940, 2.1418, 1.4969])


In [ ]:
x = torch.randn(3, requires_grad=True)
x.requires_grad_(False) # stops tracking history
print(x)
x.detach() # same as above; makes copy
print(x)
with torch.no_grad(): # same as above
    y = x + 2
    print(y)


tensor([-0.2028,  1.3495, -0.3696])
tensor([-0.2028,  1.3495, -0.3696])
tensor([1.7972, 3.3495, 1.6304])


In [ ]:
# dummy
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_() # resets gradients to zero

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()

# Backpropagation

In [ ]:
import torch

In [ ]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y)**2
print(loss)

# backward pass
loss.backward()
print(w.grad)

# update weights
# next forward and backward pass

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


# Gradient Descent Using Autograd